version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: proxy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  
    volumes:
      - mysql_data:/var/lib/mysql  
    networks:
      - backend 

  mqtt-broker:
    image: vernemq/vernemq
    container_name: mqtt-broker
    ports:
      - "1883:1883" 
      - "8080:8080" 
    environment:
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
    networks:
      - backend  

  proxy:
    build:
      context: ./proxy
    container_name: proxy
    ports:
      - "1884:1884"
      - "1885:1885"
    depends_on:
      - mysql  
      - mqtt-broker
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/proxy"  
    networks:
      - backend  

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8081:8081"
    depends_on:
      - mysql 
      - mqtt-broker
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/proxy"  
    networks:
      - backend  

volumes:
  mysql_data:

networks:
  backend:  
