FROM golang:1.23.4 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd ./cmd
COPY ./database ./database
COPY ./handlers ./handlers
COPY ./models ./models
COPY ./mqtt ./mqtt
COPY ./proxies ./proxies

WORKDIR /app/cmd

RUN go build -o /app/main .

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/main .

EXPOSE 1884 1885

CMD ["./main"]
